package schemadict

import (
	"os"
	"strings"

	"github.com/codex-k8s/hrm-sql-mcp/internal/spfile"
)

// Column is one row of a table's 欄位定義 section.
type Column struct {
	// Ordinal is the 序號 as written, kept as text because the file is not
	// guaranteed to number every table from one.
	Ordinal string `json:"ordinal,omitempty"`
	// Name is the column identifier.
	Name string `json:"name"`
	// Description is the Chinese 中文說明, the reason this file exists.
	Description string `json:"description,omitempty"`
	// Type is the declared 資料型別.
	Type string `json:"type,omitempty"`
	// Nullable is the 允許空值 cell, verbatim.
	Nullable string `json:"nullable,omitempty"`
	// KeyMarked reports that the 主鍵 cell held something other than a blank.
	// What it held is not interpreted; see the package comment.
	KeyMarked bool `json:"key_marked,omitempty"`
	// Remark is the 備註 cell, verbatim.
	Remark string `json:"remark,omitempty"`
}

// Table is one "# 資料表：" section.
type Table struct {
	Name string `json:"name"`
	// System is the 所屬系統 line, which groups tables by business area.
	System  string   `json:"system,omitempty"`
	Note    string   `json:"note,omitempty"`
	Columns []Column `json:"columns,omitempty"`
	// Line is where the section starts, so a caller can cite the source.
	Line int `json:"line,omitempty"`
}

// Dict is a parsed dictionary.
type Dict struct {
	Path   string
	Tables []Table
}

// Load reads and parses a dictionary file.
func Load(path string) (*Dict, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	// The same decoder as the SQL scripts. This file is UTF-8 today, but it is
	// generated by a tool nobody here controls, and a silently mojibaked
	// dictionary would poison every search result with plausible nonsense.
	text, _, err := spfile.Decode(raw)
	if err != nil {
		return nil, err
	}
	d := Parse(text)
	d.Path = path
	return d, nil
}

const tableHeading = "# 資料表："

// Parse reads dictionary text.
//
// It is a line scanner rather than a Markdown parser: the file is machine
// generated with a fixed shape, and the parts that vary are the ones a real
// Markdown parser would not help with anyway.
func Parse(text string) *Dict {
	d := &Dict{}
	var cur *Table
	inColumns := false

	for i, line := range strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n") {
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, tableHeading):
			d.Tables = append(d.Tables, Table{
				Name: strings.TrimSpace(strings.TrimPrefix(trimmed, tableHeading)),
				Line: i + 1,
			})
			cur = &d.Tables[len(d.Tables)-1]
			inColumns = false

		case cur == nil:
			// Preamble before the first table.

		case strings.HasPrefix(trimmed, "**所屬系統**："):
			cur.System = clean(strings.TrimPrefix(trimmed, "**所屬系統**："))

		case strings.HasPrefix(trimmed, "**說明**："):
			cur.Note = clean(strings.TrimPrefix(trimmed, "**說明**："))

		case trimmed == "## 欄位定義":
			inColumns = true

		case strings.HasPrefix(trimmed, "## "):
			// Any other heading ends the column table. In particular
			// "## 欄位說明", which is template output and must not be read.
			inColumns = false

		case inColumns && strings.HasPrefix(trimmed, "|"):
			if col, ok := parseColumnRow(trimmed); ok {
				cur.Columns = append(cur.Columns, col)
			}
		}
	}
	return d
}

// parseColumnRow reads one Markdown table row, skipping the header and the
// |---|---| separator.
func parseColumnRow(line string) (Column, bool) {
	cells := splitRow(line)
	if len(cells) < 4 {
		return Column{}, false
	}
	// The separator row and the header row are both recognisable without
	// counting lines, which keeps this robust to a table gaining a title row.
	if strings.HasPrefix(cells[0], "---") || cells[1] == "欄位名稱" || cells[0] == "序號" {
		return Column{}, false
	}
	c := Column{
		Ordinal:     clean(cells[0]),
		Name:        clean(cells[1]),
		Description: clean(cells[2]),
		Type:        clean(cells[3]),
	}
	if len(cells) > 4 {
		c.Nullable = clean(cells[4])
	}
	if len(cells) > 5 {
		c.KeyMarked = clean(cells[5]) != ""
	}
	if len(cells) > 6 {
		c.Remark = clean(cells[6])
	}
	if c.Name == "" {
		return Column{}, false
	}
	return c, true
}

func splitRow(line string) []string {
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	parts := strings.Split(line, "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

// clean trims a cell and turns the generator's "nan" placeholder into empty.
func clean(s string) string {
	s = strings.TrimSpace(s)
	if strings.EqualFold(s, "nan") {
		return ""
	}
	return s
}

// TableByName finds a table, case-insensitively.
func (d *Dict) TableByName(name string) (Table, bool) {
	for _, t := range d.Tables {
		if strings.EqualFold(t.Name, name) {
			return t, true
		}
	}
	return Table{}, false
}
